### PR TITLE
Test: Run CI on Master (don't merge)

### PR DESCRIPTION
**Pull request by chrisohaver**
Testing master...

### CODE REVIEW

**Comment by chrisohaver** [comment]
The test is failing - but in a way that the CI framework is not detecting... i.e. the test is crashing before it completes.  But in CI framework fails to detect and marks 1/1 pass... when in fact there are 2 tests and one fails to complete.

**Comment by chrisohaver** [comment]
fixed false negative test result in coredns/ci#61.

Now the "real" error can be seen...

**Comment by chrisohaver** [comment]
Timing issue in test set up?  It passed (legitimately) once above...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/kubernetai] Test: Run ..." ]
>Timing issue in test set up?  It passed (legitimately) once above...

I had to reboot the box... Could build docker containers and friends after that, 
may or may not be related...

**Comment by chrisohaver** [comment]
Thanks for letting me know.  Though I don't think its related.

**Pull request closed without merging**
